spring:
  datasource:
    url: jdbc:mysql://localhost:3307/security
    username: root
    password: Hello@clock1233
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

security-key: secret